### ISSUE TITLE
Site has an untrusted SSL certificate

### ISSUE THREAD

**Issue by SpacyRicochet** [PeridexisErrant/DF-Walkthrough#1]
Using OSX Yosemite, completely updated. Not on El Cap yet :)

**Comment by PeridexisErrant** [comment]
I've heard of a few people having trouble with this when redirecting from `http[s]://*.rtfd.org` to `readthedocs`, so that might be the problem.

Either way I don't control the domain though, they're just the best host for this kind of documentation.

**Comment by SpacyRicochet** [comment]
Yup, I noticed that. Seems fixed at the moment too, so that's a good thing. Enjoying your walkthrough!
