### ISSUE TITLE
Adding brew task fails unless you have some empty barrels

### ISSUE THREAD

**Issue by SpacyRicochet** [PeridexisErrant/DF-Walkthrough#2]
I got stuck on adding a brew task in the still. After typing `q`, `a`, `b`, I get the following screen; 

![screen shot 2015-11-05 at 11 20 51](https://cloud.githubusercontent.com/assets/904596/10965794/95fd3892-83af-11e5-8520-9b6db9c25954.png)

From which I can't appear to actually add the brewing task. 

Instead, I had to create the wooden barrels first and then add brew tasks. This could use a slight revision in the walkthrough.

**Comment by PeridexisErrant** [comment]
Thanks for the feedback!  It's really valuable, because I'm reading from a very different perspective.

**Comment by SpacyRicochet** [comment]
I'll keep pointing things out in the issues then! It's a blast so far :)

Maybe a smaller side section (mini-class?) on what actually happens when you don't have sufficient resources for a task (e.g. that screen happens). Or do you cover that screen later on in the walkthrough?
