### ISSUE TITLE
DF Tutorial embark inherits dead civilization

### ISSUE THREAD

**Issue by pcd1193182** [PeridexisErrant/DF-Walkthrough#4]
I downloaded the walkthrough pack and started playing, and immediately after I unpaused for the first time, one of the dwarfs promoted themself to King. I imagine this is going to make things a lot harder, having to deal with them pouting since they dont' have a noble-quality room yet.  Is there any way to deal with this?

**Comment by PeridexisErrant** [comment]
Only by starting with a different embark, but it shouldn't provide any real problems.
